- README.md
> #15 Update README.md

- docs/pull_request_template.md
> #34 Create pull_request_template.md

- README.md
#15  How to start the development server instructions are added in the readme file.
> #15 Readme File updated

- dist/main.css
- static/main.css
#45  Adjust bar corner
The CSS style has been changed to show the bar corner based on the acceptance criteria.
> #45 changing the bar corner style

- dist/main.css
- static/main.css
#51 The the chart is responsive for all screen sizes
> #51 Screen Responsive for all screen widths

- src/utility/methods.js
> #70 fixes sorting bars bug

- package-lock.json
- src/index.ts
- src/renderer.ts
- src/stackedBars.ts
- static/index.html
- static/main.css
This PR implements bars using the D3 library and the Pareto data structure. 
In the future we will need to use the API values for the styling. (height, width, color). 
closes #83
> #83 Implement bars in d3

- package-lock.json
- package.json
- src/index.ts
- src/renderer.ts
- src/settings.ts
Added settings interface and data transformation for setting layer
> #82 Settings layer

- package-lock.json
- src/axis.ts
- src/cumulativeLine.ts
- src/index.ts
- src/renderer.ts
- src/stackedBars.ts
Cumulative line implemented in D3 with Typescript. 
- Using the category labels and cumulative percentage to get the x and y values
- Calculating where the line is rendered based on the bar width
- Some measurements are changed (margins are removed)  in the stackedBars to match the line
- In our previous code we curved the line using .curve(d3.curveMonotoneX), this was removed and the line is now segmented as requested
Closes #65 
Closes #67
> #65 Cumulative line refactor

- package-lock.json
- src/cumulativeLine.ts
Change the method data type to using array map to create the positions array![image](https://user-images.githubusercontent.com/102019782/203268688-ce96096f-e8cd-44e9-a5c1-98dfa3f605c9.png)
> Use Array.map to create the positions array.

- src/axis.ts
- src/cumulativeLine.ts
- src/index.ts
- src/renderer.ts
- src/stackedBars.ts
Fix syntax and namings based on Tibco's feedback.
- Remove async where needed
- Remove parantheses in return statements
- Remove old unused code
- Remove todo that was already fixed
- Change some variable names _(reviewer should check and approve)_
- Change leaf.key to leaf.formattedValue()
closes #108
> #108 Fix syntax and namings based on feedback

- src/axis.ts
- src/cumulativeLine.ts
- src/index.ts
- src/pareto.ts
closes #111 
Use leafIndex for identifying x position
- Get leafIndex from the Spotfire API to use instead of label
- Add variables to the interfaces
- Add function to get an array of indices
> #111 Use index for identifying stacked bar data

- src/axis.ts
- src/cumulativeLine.ts
- src/index.ts
- src/pareto.ts
Reverts MajaLinder/SEMFIRE#121
> Revert "#111 Use index for identifying stacked bar data"

- src/axis.ts
- src/cumulativeLine.ts
- src/index.ts
- src/pareto.ts
- src/renderer.ts
- src/settings.ts
- src/stackedBars.ts
Closes #106  
- Changed initialization format to remove unnecessary casting for the interfaces
> #106 Removed casting

- static/mod-manifest.json
#101  Drag and drop label's respect the axis names 
closes #101
> Drag and drop

- src/index.ts
- static/mod-manifest.json
#98 Add a space in the axis names
closes #98
> #98 Add space in axis names

- src/index.ts
closes #115 
Based on feedback from Tibco, the data transformation has been extracted to a method. It takes the root node and a boolean that checks the color axis as parameters and returns a pareto object.
> #115 Extract data transformation to a method

- src/axis.ts
- src/cumulativeLine.ts
- src/stackedBars.ts
#112  change the types
The data types have been changed except for two as we agreed in the meeting.
> #112 change the types

- src/axis.ts
- src/index.ts
- src/renderer.ts
#105 Fix the overlapping issue 
The text of the axis can show part of it when the data is too much, and when the mouse is hovering on it, it will show the complete value and words by tooltips.
closes #105
> Category ticks

- src/index.ts
- src/pareto.ts
- src/renderer.ts
- src/stackedBars.ts
#104 Add tooltip support for bars
When user hovers over a bar it displays some information in a tooltip. 
I also added a todo comment in the code since I noticed that if the user selects none for value or category axis we get an error. 
closes #104 
With Color By
With Color by as none
With Color by as sum
> Add tooltip support for bars

- src/axis.ts
- src/resources.ts
#141 
Hardcode the padding of the axis and add a tooltip if the value is larger than expected can use tooltip to see the value.
> #141 Mod padding

- src/stackedBars.ts
> #156 bugfix on mousover selection

- static/mod-manifest.json
#109  Defaultvisibility -> visible
change dafaultvisibilty on category and value axis to be visible
closes #109
> #109 change default visibilty

- src/cumulativeLine.ts
#153 Scatter dots
Added scatter dots to the cumulative line to be able to implement a tooltip on them
> #153 add scatter dots to the cumulative line

- src/axis.ts
- src/index.ts
- src/renderer.ts
- src/settings.ts
- src/stackedBars.ts
Store tooltip in settings to improve code quality
> Store tooltip in settings

- src/cumulativeLine.ts
#161 Adjust cumulative line weight
Hardcode the cumulative line weight to be same as the example.
> #161 Adjust cumulative line weight

- src/stackedBars.ts
#175 Cutoff line is clickable even between the dashed lines
Add a line in the background to fix issue with being unable to click inbetween dashed lines
closes #175
> 8020marking
